server:
  port: 8090



#JdbcTemplate
spring:
  datasource:
    url: jdbc:mysql://192.168.1.212:3309/10002?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
#########redis配置###############
  redis:
    host: 127.0.0.1
    port: 6379
    password:
# 连接超时时间（毫秒）
    timeout: 10000
# Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    lettuce:
      pool:
# 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
# 连接池中的最大空闲连接 默认 8
        max-idle: 8
# 连接池中的最小空闲连接 默认 0
        min-idle: 0
  swagger:
    base-package: com.xy
    enabled: true
#设置监控配置帐号密码
  security:
    user:
      name: admin
      password: 123456
      roles: SUPERUSER


mybatis:
  mapper-locations: classpath:com/xy/studyboot/mapper/*.xml
  type-aliases-package: com.xy.studyboot.pojo
  configuration:
    map-underscore-to-camel-case: true

########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql






logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR



